---
title: "data-explore"
author: "Ben"
date: "6/16/2018"
output: html_document
---

```{r libs}
rm(list=ls())
library(ggthemes)
library(jsonlite)
library(tidyverse)
```

```{r options}
options(stringsAsFactors = FALSE)
```



# Reproduce Fig 5.

```{r}
f_all_data <- "../data/df_agg.csv"
dfAll <- read.csv(f_all_data)
```

```{r}
dfAll %>%
  filter(condition=='combined') %>%
  select(IP, condition, label, conditional_trial_num, label_type, display_type) %>%
  group_by(conditional_trial_num, display_type)
  
```


```{r}
dfAll %>%
  filter(condition=='combined') %>%
  select(IP, condition, label, conditional_trial_num, label_type, display_type) %>%
  mutate(wordLength=nchar(label)) %>%
  group_by(conditional_trial_num, display_type) %>%
  summarise(n=n(),
            avgLen=mean(wordLength),
            ci_high=avgLen+1.96*sd(wordLength)/sqrt(n),
            ci_low=avgLen-1.96*sd(wordLength)/sqrt(n)) %>%
  ggplot(aes(x=conditional_trial_num, y=avgLen, col=display_type)) +
    geom_point() +
    geom_line() +
    geom_errorbar(aes(ymax=ci_high, ymin=ci_low), col='grey', alpha=0.7, width=0.5) +
    ylim(3, 7) +
    theme_few() +
    ggtitle("Reproducing Fig 5.")
```


```{r}
dfPropData <- dfAll %>%
  filter(condition=='combined') %>%
  select(IP, condition, label, conditional_trial_num, label_type, display_type) %>%
  mutate(isShortLabel=label_type=='short') %>%
  group_by(conditional_trial_num, display_type) %>%
  summarise(n=n(),
            propShort=mean(isShortLabel),
            ci_high=propShort+1.96*sqrt(propShort*(1-propShort)/n),
            ci_low=propShort-1.96*sqrt(propShort*(1-propShort)/n))

dfPropData %>%
  ggplot(aes(x=conditional_trial_num, y=propShort, col=display_type)) +
    geom_errorbar(aes(ymax=ci_high, ymin=ci_low)) +
    geom_line() +
    ylim(0, 1) +
    theme_few() +
    ggtitle("Proportion of times using the short form over repetition.")

# write.csv(dfPropData, "../data/temporalDynamicsData.csv")
```



```{r data}
df <- read.csv("../data/d _agg.csv")
```

```{r add-match-label}
df <- df %>%
  mutate(match=label_type_num==display_type_num)
```

```{r get-conditions}
conditions <- unique(df$condition)
```


```{r plotting-helpers}
plot_IP_behavior_match <- function(cond, df, save_file=TRUE) {
  test_img <- df %>%
    filter(condition == cond) %>%
    ggplot(aes(x=as.factor(trial), y=match, col=display_type, group=1)) +
      geom_point(aes(shape=label_type), size=3) +
      geom_line() +
      theme_few() +
      facet_wrap(~IP, ncol=5) +
      ggtitle(paste("Condition:", cond)) +
      theme(text = element_text(size=12),
            axis.text.x = element_text(angle=90, hjust=1, size=6),
            plot.title = element_text(hjust = 0.5))
  if (save_file) ggsave(paste0("img/test-img-", cond, "-20180616.png"), test_img, width=30, height=30)
}

plot_IP_behavior_label_type <- function(cond, df, save_file=TRUE) {
  test_img <- df %>%
    filter(condition == cond) %>%
    ggplot(aes(x=as.factor(trial), y=label_type, col=display_type, group=1)) +
      geom_point(size=3, alpha=0.5) +
      geom_line() +
      theme_few() +
      facet_wrap(~IP+condition, ncol=5) +
      ggtitle(paste("Condition:", cond)) +
      theme(text = element_text(size=24),
            axis.text.x = element_text(angle=90, hjust=1, size=6),
            plot.title = element_text(hjust = 0.5))
  if (save_file) ggsave(paste0("img/label-type-", cond, "-20180616.png"), test_img, width=30, height=30)
}
```

```{r plots}
for (i in 1:length(conditions)) {
  cond <- conditions[i]
  cat(paste("\nCondition:", cond))
  plot_IP_behavior_match(cond, df)
  plot_IP_behavior_label_type(cond, df)
}
```

```{r bad-ips}
plot_IP_behavior_label_type("accuracy", df)
```




